# Generated by Django 5.1.6 on 2025-02-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
