# Generated by Django 5.1.6 on 2025-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_payment_deposit_amount_payment_installment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
