# Generated by Django 5.1.6 on 2025-02-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_payment_due_amount_payment_paid_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='remaining',
            new_name='remaining_paid_amount',
        ),
    ]
