# Generated by Django 5.1.6 on 2025-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_remaining_payment_remaining_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
