# Generated by Django 5.1.6 on 2025-02-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_booking_total_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
