# Generated by Django 5.1.6 on 2025-02-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_payment_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
