# Generated by Django 5.1.6 on 2025-02-27 12:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_booking_installment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='price_per_biweekly',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_per_week',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
