# Generated by Django 5.1.6 on 2025-02-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_service_price_service_price_per_biweekly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_months',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
