# Generated by Django 5.1.6 on 2025-02-28 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_payment_due_months_payment_paid_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_datetime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
