# Generated by Django 5.1.6 on 2025-02-28 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_payment_paid_date_payment_paid_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
