# Generated by Django 5.1.6 on 2025-03-03 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_payment_paid_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='deposit_amount',
            new_name='partial_amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
